dtb-$(CONFIG_ARCH_ROCKCHIP) += \
  rk3399-armsbc-dca.dtb \
  rk3566-armsbc-dca.dtb \
  rk3568-armsbc-dca.dtb \
  rk3568-armsbc-kick.dtb \
  rk3568-armsbc-nano.dtb \
  rk3568-armsbc-ykr.dtb \
  rk3576-armsbc-edge.dtb \
  rk3576-armsbc-ido.dtb \
  rk3588-armsbc-dca.dtb \
  rk3588-armsbc-edge.dtb \
  rk3588-armsbc-kick.dtb \
  rk3588-armsbc-rwa.dtb \
